name: card_organizer
description: A Flutter app for organizing cards into folders with SQLite database.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # SQLite Database
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  # State Management (optional but useful)
  provider: ^6.1.2

  # Image Picker (optional for card images)
  image_picker: ^1.0.7

  # File Management (if storing images locally)
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
